### ISSUE TITLE
learn package management

### ISSUE THREAD

**Issue by ashleygould** [weednix/from_dead_zero#11]
https://en.wikipedia.org/wiki/Package_manager
https://wiki.debian.org/PackageManagement

**Comment by SRSGitHub** [comment]
- List install packages
- Get info on a package
- Search for packages
- When was package installed?
- What packages depend on this package?
- What packages are required for this package?
- What files are in this package?
- What package does this file belong to?
- What documentation for this package?
- Install package
- Delete package
- How do I search for a package based on a command name or library name?*
- Package repositories
- List configured repositories
- Create a new repository configuration
